---
title: "Advanced Geospatial Mapping with R and Leaflet"
author: "SCIP"
date: "14/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

- Advanced geospatial mapping for humanists and social scientists
- Replication of [ABC News article](https://www.abc.net.au/news/2020-07-31/coronavirus-near-me-victoria-melbourne-postcode-data-covid19/12513684). Data provided by ABS (updated since the publication of this article)
- Merge this with mock crime data and add various parameters as needed
- Make an interactive map with two layers

## Tools

- R/Leaflet package
- Previous tutorial on geomapping for non-programmers went over user-friendly options (e.g., ArcGIS StoryMaps)
- Advantages: free and open source, more control over parameters, customisation and output
- "Programming" vs. point-and-click approaches
- Disadvantages: learning curve, potential future use, time investment

## Goals

- GIS and geospatial mapping is a semester-long course
- For a detailed introduction to advanced GIS approaches, see [this e-book](https://mgimond.github.io/Spatial/index.html)
- We will touch on the hands-on elements in this tutorial

## Basic concept

- A variable in your dataset with a geographic component (e.g., country, state, city name, full street address) for plotting points
- A way to geocode the above address
- Shapefiles that correspond with the polygon boundaries
- A shapefile is a simple, nontopological format for storing the geometric location and attribute information of geographic features. Geographic features in a shapefile can be represented by points, lines, or polygons (areas)

## Things to consider

- Data format and structure
- Recoding and reformatting
- Points or boundaries
- Single or multiple layers
- Aesthetics and color schemes
- Additional functional components
- Hosting the map online

## Useful links

[Install RStudio (choose FREE version)](https://www.rstudio.com/products/rstudio/download/)

[`leaflet` package in R](https://rstudio.github.io/leaflet/)

[`leaflet` package documentation](https://cran.r-project.org/web/packages/leaflet/leaflet.pdf)

[`leaflet` in Python](https://programminghistorian.org/en/lessons/mapping-with-python-leaflet)

[Leaflet base maps](https://leaflet-extras.github.io/leaflet-providers/preview/)

[`sf` package](https://r-spatial.github.io/sf/articles/sf1.html)

[`absmapsdata` package](https://github.com/wfmackey/absmapsdata)

[`tidygeocoder` package](https://rdrr.io/cran/tidygeocoder/man/tidygeocoder-package.html)

[R color palettes](https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/)

[Free GIS options](https://gisgeography.com/free-gis-software/)

[UniMelb Resources](https://unimelb.libguides.com/GIS)

Happy mapping!







